:actor_name:_objective
/home/diptesh/anaconda3/envs/aggDet/lib/python3.8/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
  0%|          | 0/570 [00:00<?, ?it/s][ERROR 2022-07-12 17:49:30,881] function_runner.py: 286  Runner Thread raised error.
Traceback (most recent call last):
  File "/home/diptesh/anaconda3/envs/aggDet/lib/python3.8/site-packages/ray/tune/function_runner.py", line 277, in run
    self._entrypoint()
  File "/home/diptesh/anaconda3/envs/aggDet/lib/python3.8/site-packages/ray/tune/function_runner.py", line 349, in entrypoint
    return self._trainable_func(
  File "/home/diptesh/anaconda3/envs/aggDet/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 462, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/home/diptesh/anaconda3/envs/aggDet/lib/python3.8/site-packages/ray/tune/function_runner.py", line 645, in _trainable_func
    output = fn()
  File "/home/diptesh/anaconda3/envs/aggDet/lib/python3.8/site-packages/transformers/integrations.py", line 288, in dynamic_modules_import_trainable
    return trainable(*args, **kwargs)
  File "/home/diptesh/anaconda3/envs/aggDet/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 410, in inner
    trainable(config, **fn_kwargs)
  File "/home/diptesh/anaconda3/envs/aggDet/lib/python3.8/site-packages/transformers/integrations.py", line 189, in _objective
    local_trainer.train(resume_from_checkpoint=checkpoint, trial=trial)
  File "/home/diptesh/anaconda3/envs/aggDet/lib/python3.8/site-packages/transformers/trainer.py", line 1409, in train
    return inner_training_loop(
  File "/home/diptesh/anaconda3/envs/aggDet/lib/python3.8/site-packages/transformers/trainer.py", line 1651, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/diptesh/anaconda3/envs/aggDet/lib/python3.8/site-packages/transformers/trainer.py", line 2345, in training_step
    loss = self.compute_loss(model, inputs)
  File "/tmp/ipykernel_2157418/3804557109.py", line 6, in compute_loss
AttributeError: 'dict' object has no attribute 'to'
